version: 2.1

.dockersetup: &dockersetup
  docker:
    - image: chenyingzhao/fsub_extractor_deps:0.0.1
  working_directory: /fsub_extractor


runinstall: &runinstall
    name: Install fsub_extractor
    command: |
      VERSION=0+build
      if [[ -n "$CIRCLE_TAG" ]]; then
        VERSION="$CIRCLE_TAG"
      fi
      git checkout $CIRCLE_BRANCH
      echo "${VERSION}" > /src/qsiprep/qsiprep/VERSION
      echo "include qsiprep/VERSION" >> /src/qsiprep/MANIFEST.in
      pip install . --progress-bar off
      # Precaching fonts, set 'Agg' as default backend for matplotlib
      python -c "from matplotlib import font_manager"
      sed -i 's/\(backend *: \).*$/\1Agg/g' $( python -c "import matplotlib; print(matplotlib.matplotlib_fname())" )

jobs:

  build:
    <<: *dockersetup
    steps:
      - checkout
      - run: *runinstall
  test_working:
    <<: *dockersetup
    steps: 
      - checkout
      - run: *runinstall
      - run:
          name: Test command extrator is working
          command: |
            extractor
      # can add more runs for different commands if needed
      
workflows:
  version: 2
  build_test_deploy:
    jobs:

      - build:
          filters:
            tags:
              only: /.*/

      - test_working:
          requires:
            - build
          filters:
            tags:
              only: /.*/